[edge_vps]
edge1 ansible_host=203.0.113.10

[openstack_edge_nodes]
edge-node1 ansible_host=edge-node1.example.net edge_node_id=1
edge-node2 ansible_host=edge-node2.example.net edge_node_id=2
edge-node3 ansible_host=edge-node3.example.net edge_node_id=3
